import { pgTable, uuid, varchar, boolean, jsonb, index } from 'drizzle-orm/pg-core';
import timestamps from "../common"
import { users } from '../user';



/// This table stores referral codes generated by users
/// Each user can have one active referral code at a time
/// Codes are unique and can be used by others to refer new users
export const referralCodes = pgTable('referral_codes', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).unique().notNull(),
  code: varchar('code', { length: 11 }).notNull().unique(),
  isActive: boolean('is_active').default(true),

  metadata: jsonb("metadata"), /// e.g. UTM params, channel id
  ...timestamps
},
  (t) => [
    index("referral_codes_user_idx").on(t.userId),
  ]
)